#ifndef NEBULA_LANG_INSTRUCTION_H
#define NEBULA_LANG_INSTRUCTION_H

enum INSTRUCTION {
    I_FETCH,
    I_STORE,
    I_PUSH,
    I_POP,
    I_ADD,
    I_TERMINATE,
};

#endif //NEBULA_LANG_INSTRUCTION_H
